---
- name: Install Apache
  become: yes
  apt: pkg=apache2 state=latest

- name: Install Apache Modules
  become: yes
  apache2_module: state=present name={{ item }}
  notify: restart apache
  with_items:
    - rewrite
    - vhost_alias
    - headers
    - expires
    - filter

- name: Uninstall Apache Modules for mailhog
  become: yes
  apache2_module: state=absent name={{ item }}
  when: not mailhog.install
  notify: restart apache
  with_items: mailhog.apache_modules|reverse|list

- name: Install Apache Modules for mailhog
  become: yes
  apache2_module: state=present name={{ item }}
  when: mailhog.install
  notify: restart apache
  with_items: mailhog.apache_modules

- include: ssl.yml
#  when: apache.vhosts is defined

- shell: apache2 -v
  register: apache_version

- include: vhosts.yml vhost_template=vhost24.conf.tpl.j2
  when: apache.vhosts is defined and apache_version.stdout.find('Apache/2.4.') != -1

- include: vhosts.yml vhost_template=vhost22.conf.tpl.j2
  when: apache.vhosts is defined and apache_version.stdout.find('Apache/2.2.') != -1

- name: Change user of apache service
  become: yes
  lineinfile: "dest=/etc/apache2/envvars regexp=\"APACHE_RUN_USER\" line=\"export APACHE_RUN_USER={{ apache.user }}\" owner=root group=root mode=0644"
  notify: restart apache

- name: Change group of apache service
  become: yes
  lineinfile: "dest=/etc/apache2/envvars regexp=\"APACHE_RUN_GROUP\" line=\"export APACHE_RUN_GROUP={{ apache.group }}\" owner=root group=root mode=0644"
  notify: restart apache
