#!/bin/bash

### BEGIN INIT INFO
# Provides:          mailhog
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: mailhog dummy e-mail server with web interface
### END INIT INFO

MAILHOG="{{ mailhog.start_script }}"
case "$1" in
  start)
    echo -n "Starting: mailhog"

    pid=`ps x -o "%c" | \grep mailhog_start`

    if [[ ! -n $pid ]]
    then
      start-stop-daemon --start --quiet --background --exec $MAILHOG
      echo "."
    else
      echo ". already started!"
    fi

    ;;
  stop)
    echo -n "Stopping: mailhog"

    pid=`ps x -o "%p %c" | \grep mailhog_start | awk '{ print $1; }'`

    if [[ -n $pid ]]
    then
      pgid=`ps x -o "%p %r" | \grep $pid | awk '{ print $2; }'`
      kill -TERM -- -$pgid
      echo "."
    else
      echo ". Process not started yet!"
    fi
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    pid=`ps x -o "%c" | \grep mailhog_start`

    if [[ ! -n $pid ]]
    then
      echo "Not started."
      exit 3
    else
      echo "Started."
      exit 0
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/mailhog {start|stop|restart}"
    exit 1
esac

exit 0
