#!/bin/bash

VERSION=$1;

declare -A VERSIONS
VERSIONS["5.3"]="5.3.29"
VERSIONS["5.4"]="5.4.45"
VERSIONS["5.5"]="5.5.31"
VERSIONS["5.6"]="5.6.17"
VERSIONS["7.0"]="7.0.2"

if [[ ! -z ${VERSION} && ! -z ${VERSIONS[$VERSION]} ]] ; then
    VERSION="${VERSIONS[$VERSION]}"
fi

echo ${VERSION}